---
- project:
    name: corenic/corenic-docs
    check:
      jobs:
        - linters
        - build-sphinx-docs:
            success-url: 'singlehtml/'
            vars:
              sphinx_source_dir: "doc"
              sphinx_build_dir: "build"
              sphinx_builders:
                - singlehtml
                - spelling

    gate:
      jobs:
        - build-sphinx-docs:
            success-url: 'singlehtml/'
            vars:
              sphinx_source_dir: "doc"
              sphinx_build_dir: "build"
              sphinx_builders:
                - singlehtml

    post:
      jobs:
        - build-sphinx-docs:
            success-url: 'singlehtml/'
            vars:
              sphinx_source_dir: "doc"
              sphinx_build_dir: "build"
              sphinx_builders:
                - singlehtml
        - freshdesk-doc-upload:
            dependencies:
              - build-sphinx-docs
            vars:
              article_category: "Agilio SmartNICs"
              article_folder: "Agilio SmartNIC - Basic Firmware"
              article_title: "Basic Firmware User Guide"
              article_location: "{{ sphinx_artifacts_url }}/index.html"
